#!/bin/bash


## Load the required modules
module load mpt
module load intel-compilers-19

## compile


## compile with MPI:
mpicxx amair_wave_parallel_horiz20.cpp  -o amair_wave_parallel_horiz20.exe

## remove object files if there is any!:
# rm *.mod
# rm *.o

